name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_WRITE }}
        run: |
          git push --force https://Zadif123:$HF_WRITE@huggingface.co/spaces/Zadif123/panorama-api main